### ISSUE TITLE
AttributeError: 'ClientTlsContext' object has no attribute '_certificate_source'

### ISSUE THREAD

**Issue by alexw23** [mmalolepszy/hon-revived#58]
Having issues after latest update with HA

**Environment (please complete the following information):**
 - Home Assistant Version: 2026.7.4
 - hOn Integration Version 0.19.1

```
This error originated from a custom integration.

Logger: custom_components.hon
Source: config_entries.py:798
Integration: Haier hOn Revived (documentation, issues)
First occurred: 10:30:02 AM (1 occurrence)
Last logged: 10:30:02 AM

Error setting up entry XXXXXXXX for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 34, in async_setup_entry
    hon = await Hon(
          ^^^^^^^^^^
    ...<6 lines>...
    ).create()
    ^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pyhon/hon.py", line 77, in create
    await self.setup()
  File "/usr/local/lib/python3.14/site-packages/pyhon/hon.py", line 123, in setup
    self._mqtt_client = await MQTTClient(self, self._mobile_id).create()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pyhon/connection/mqtt.py", line 38, in create
    await self._start()
  File "/usr/local/lib/python3.14/site-packages/pyhon/connection/mqtt.py", line 137, in _start
    await loop.run_in_executor(None, MQTTClient._build_mqtt_client, self, aws_token)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.14/site-packages/pyhon/connection/mqtt.py", line 141, in _build_mqtt_client
    self._client = mqtt5_client_builder.websockets_with_custom_authorizer(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        endpoint=const.AWS_ENDPOINT,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        on_publish_received=self._on_publish_received,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/awsiot/mqtt5_client_builder.py", line 754, in websockets_with_custom_authorizer
    return _builder(tls_ctx_options=tls_ctx_options,
                    use_websockets=True,
    ...<2 lines>...
                    websocket_proxy_options=websocket_proxy_options,
                    **kwargs)
  File "/usr/local/lib/python3.14/site-packages/awsiot/mqtt5_client_builder.py", line 342, in _builder
    client = awscrt.mqtt5.Client(client_options=client_options)
  File "/usr/local/lib/python3.14/site-packages/awscrt/mqtt5.py", line 1827, in __init__
    self._metrics = _create_metrics_mqtt5(client_options)
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/awscrt/aws_iot_metrics.py", line 473, in _create_metrics_mqtt5
    crt_feature_list = _get_encoded_feature_list(client_options)
  File "/usr/local/lib/python3.14/site-packages/awscrt/aws_iot_metrics.py", line 300, in _get_encoded_feature_list
    val = _certificate_source_metrics_value(client_options.tls_ctx._certificate_source)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientTlsContext' object has no attribute '_certificate_source'
```

**Comment by snattanzi** [comment]
Same Issue that I noticed only after upgrading to 2026.7.4. Same exact log. It seems that the integration uses the pyhon library, which tries to open an MQTT connection to Haier’s servers through AWS libraries:

- awsiot
- awscrt
- MQTT 5
- TLS/WebSocket

While creating the connection, awsiot looks for this internal attribute "ClientTlsContext._certificate_source"

However, the installed version of awscrt does not contain it. Python therefore raises this error: "AttributeError: 'ClientTlsContext' object has no attribute '_certificate_source'"

It seems that this is most likely a version incompatibility between awsiotsdk and awscrt, possibly triggered by Home Assistant running on Python 3.14.

**Comment by alexw23** [comment]
#57 covers pinning the library versions in pyhon-revived. I'll make a fork later today that either pins or updates the code.

**Comment by BWeesy** [comment]
I see the 
`AttributeError: 'ClientTlsContext' object has no attribute '_certificate_source'"` at the same place with MQTT5. I'm running python 3.14 also.
HA version 2026.7.4
Hon-revived 0.19.1

**Comment by mmalolepszy** [comment]
I have just released [v0.19.2](https://github.com/mmalolepszy/hon-revived/releases/tag/v0.19.2) version of the integration. It copies the solution suggested by @chasebolt here https://github.com/dahlb/hatch_rest_api/pull/71 i.e. disabling AWS telemetry, so the failing part won't be executed at all. 

But that's unfortunately only a workaround. The root cause of the issue is awscrt python library being misaligned with underlying awscrt native C library. This is also most likely the cause of #49 and #57. Pinning the specific version of awsiotsdk package won't help as the issue is deeper in the dependency tree.

@alexw23 @snattanzi @BWeesy please provide more information about your instances: are you running HAOS or Docker? Do you use other integrations that use AWS SDK underneath?

**Comment by snattanzi** [comment]
> I have just released [v0.19.2](https://github.com/mmalolepszy/hon-revived/releases/tag/v0.19.2) version of the integration. It copies the solution suggested by [@chasebolt](https://github.com/chasebolt) here [dahlb/hatch_rest_api#71](https://github.com/dahlb/hatch_rest_api/pull/71) i.e. disabling AWS telemetry, so the failing part won't be executed at all.
> 
> But that's unfortunately only a workaround. The root cause of the issue is awscrt python library being misaligned with underlying awscrt native C library. This is also most likely the cause of [#49](https://github.com/mmalolepszy/hon-revived/issues/49) and [#57](https://github.com/mmalolepszy/hon-revived/issues/57). Pinning the specific version of awsiotsdk package won't help as the issue is deeper in the dependency tree.
> 
> [@alexw23](https://github.com/alexw23) [@snattanzi](https://github.com/snattanzi) [@BWeesy](https://github.com/BWeesy) please provide more information about your instances: are you running HAOS or Docker? Do you use other integrations that use AWS SDK underneath?

I'm running HAOS and i'm not aware if other integrations use AWS SDK underneath. 

I have Alexa Devices, but not sure about what it uses.

**Comment by mmalolepszy** [comment]
I have confirmed a workaround. The reinstallation of integration fixes the issue (it downloads correct awscrt binary/python lib combination). So if you don't want to update right now, you can go to HACS, click "Redownload", select the same version of integration and then restart HA.

<img width="384" height="526" alt="Image" src="https://github.com/user-attachments/assets/849897e8-b96e-4857-b6f2-ead2aa3a4840" />

**Comment by BWeesy** [comment]
I'm running HAOS, I don't think I have other integrations, and the recent fix worked perfectly for me. My washing machine and dryer are now visible in my HA setup.
